### Cadastrar um novo funcionario
POST https://localhost:5001/api/funcionario/create
Content-Type: application/json

{
    "Nome" : "Kelly",
    "Setor" : "TI",
    "Cargo": "Desenvolvedora de Software"
}

### Listar todos os funcionarios
GET https://localhost:5001/api/funcionario/list

### Buscar um funcionario pelo id
GET https://localhost:5001/api/funcionario/getbyid/1

### Deletar um funcionario pelo nome
DELETE https://localhost:5001/api/funcionario/delete/Kelly

### Alterar um funcionario
PUT https://localhost:5001/api/funcionario/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Kelly alterada",
    "Setor" : "TI",
    "Cargo": "Desenvolvedora de Software"
}
